# DEVTOP SHELL

# Interactive check
[[ $- != *i* ]] && return

# Exports
export PS1="[\\$] "
export PAGER=less
export EDITOR=vim
export TOP=htop

# Aliases
alias ..='cd ..'
alias ls='ls --color=auto'
alias la='ls -lhA --color=auto'
alias md='mkdir -p'
alias rf='rm -rf'
alias clr='clear'
#alias su='sudo -s'
alias ed='$EDITOR'
alias pa='$PAGER'
alias top='$TOP'
alias grep='grep --color=auto'
